server:
  port: ${PORT:8761}

spring:
  profiles: local   
eureka:
  instance:
    hostname:  localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
	  
---
spring:
  profiles: heroku 
eureka:
  instance:
    hostname:  localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      

