server:
  port: ${PORT:8671}

eureka:
  instance:
    hostname:  localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      

